/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ProteccionCivil;
import Modelo.Emergencia;
import Modelo.PlanProteccion;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author MiguelYanes
 */
public class MenuAddEmergencia extends javax.swing.JFrame implements ActionListener{
    private JPanel contentPane;
    private JTextField txtTipoForm;
    private JTextField txtCodigoPlanForm;
    private JTextField txtNivelForm;
    private JTextField txtActuacionesNecesariasForm;
    private JTextField txtTipo;
    private JTextField txtCodigoPlan;
    private JTextField txtNivel;
    private JTextField txtActuacionesNecesarias_1;
    
    private OyenteVista oyenteVista;
    
    private static final String BTN_VOLVER = "Volver";
    private static final String BTN_ADD_EMER = "Add Emergencia";
        
    private PlanProteccion plan;
    /**
     * Creates new form MenuAddEmergencia
     */
    public MenuAddEmergencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAddEmergencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAddEmergencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAddEmergencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAddEmergencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAddEmergencia(new ProteccionCivil()).setVisible(true);
            }
        });
    }

    public MenuAddEmergencia(OyenteVista oyenteVista) {
		this.oyenteVista = oyenteVista;
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 732, 498);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(new BorderLayout(0, 0));
		contentPane.setPreferredSize(getMaximumSize());
//		
//		JToolBar toolbar_subsistemas = new JToolBar();
//		toolbar_subsistemas.setFloatable(false);
//		contentPane.add(toolbar_subsistemas, BorderLayout.NORTH);
//		
//		JButton button_menu_principal = new JButton(" Menu Principal ");
//		
//		toolbar_subsistemas.add(button_menu_principal);
//		
//		JButton button_planes_proteccion = new JButton(" Planes de Protecci\u00F3n ");
//		button_planes_proteccion.setEnabled(false);
//		toolbar_subsistemas.add(button_planes_proteccion);
//		
//		JButton button_emergencias_alertas = new JButton(" Gesti\u00F3n de emergencias y alertas ");
//		toolbar_subsistemas.add(button_emergencias_alertas);
//		
//		JButton button_reursos_medios = new JButton(" Recursos y medios ");
//		button_reursos_medios.addActionListener(new ActionListener() {
//			public void actionPerformed(ActionEvent arg0) {
//			}
//		});
//		toolbar_subsistemas.add(button_reursos_medios);
//		
		JPanel panel_gestion_planes = new JPanel();
		contentPane.add(panel_gestion_planes, BorderLayout.SOUTH);
		panel_gestion_planes.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		
		JButton btnAddEmergencia = new JButton("A\u00F1adir Emergencia");
		panel_gestion_planes.add(btnAddEmergencia);
		btnAddEmergencia.setActionCommand(BTN_ADD_EMER);
		btnAddEmergencia.addActionListener(this);
		
		JButton btnVolver = new JButton("Volver");
		panel_gestion_planes.add(btnVolver);
		btnVolver.setActionCommand(BTN_VOLVER);
		btnVolver.addActionListener(this);
		
		JPanel panel_principal = new JPanel();
		contentPane.add(panel_principal, BorderLayout.CENTER);
		panel_principal.setLayout(new BorderLayout(0, 0));
		
		JTextField txtProteccinCivil = new JTextField();
		txtProteccinCivil.setEditable(false);
		txtProteccinCivil.setFont(new Font("Tahoma", Font.PLAIN, 26));
		txtProteccinCivil.setHorizontalAlignment(SwingConstants.CENTER);
		txtProteccinCivil.setText("A\u00F1adir Emergencia");
		panel_principal.add(txtProteccinCivil, BorderLayout.NORTH);
		txtProteccinCivil.setColumns(10);
		
		JPanel panel = new JPanel();
		panel_principal.add(panel, BorderLayout.CENTER);
		panel.setLayout(new BorderLayout(0, 0));
		
		JPanel panel_1 = new JPanel();
		panel.add(panel_1, BorderLayout.WEST);
		panel_1.setLayout(new BorderLayout(0, 0));
		panel_1.setPreferredSize(new Dimension(200,200));
		
		txtTipo = new JTextField();
		txtTipo.setEditable(false);
		txtTipo.setText("Tipo");
		panel_1.add(txtTipo, BorderLayout.NORTH);
		txtTipo.setColumns(10);
		
		JPanel panel_6 = new JPanel();
		panel_1.add(panel_6, BorderLayout.CENTER);
		panel_6.setLayout(new BorderLayout(0, 0));
		
		txtCodigoPlan = new JTextField();
		txtCodigoPlan.setEditable(false);
		txtCodigoPlan.setText("Código Plan Protección");
		panel_6.add(txtCodigoPlan, BorderLayout.NORTH);
		txtCodigoPlan.setColumns(10);
		
		JPanel panel_7 = new JPanel();
		panel_6.add(panel_7, BorderLayout.CENTER);
		panel_7.setLayout(new BorderLayout(0, 0));
		
		txtNivel = new JTextField();
		txtNivel.setEditable(false);
		txtNivel.setText("Nivel de emergencia");
		panel_7.add(txtNivel, BorderLayout.NORTH);
		txtNivel.setColumns(10);
		
		JPanel panel_8 = new JPanel();
		panel_7.add(panel_8, BorderLayout.CENTER);
		panel_8.setLayout(new BorderLayout(0, 0));
//		
//		txtActuacionesNecesarias_1 = new JTextField();
//		txtActuacionesNecesarias_1.setEditable(false);
//		txtActuacionesNecesarias_1.setText("Actuaciones necesarias");
//		panel_8.add(txtActuacionesNecesarias_1, BorderLayout.NORTH);
//		txtActuacionesNecesarias_1.setColumns(10);
//		
		JPanel panel_2 = new JPanel();
		panel.add(panel_2, BorderLayout.CENTER);
		panel_2.setLayout(new BorderLayout(0, 0));
		
		txtTipoForm = new JTextField();
		panel_2.add(txtTipoForm, BorderLayout.NORTH);
		txtTipoForm.setColumns(10);
		
		JPanel panel_3 = new JPanel();
		panel_2.add(panel_3, BorderLayout.CENTER);
		panel_3.setLayout(new BorderLayout(0, 0));
		
		txtCodigoPlanForm = new JTextField();
		panel_3.add(txtCodigoPlanForm, BorderLayout.NORTH);
		txtCodigoPlanForm.setColumns(10);
		
		JPanel panel_4 = new JPanel();
		panel_3.add(panel_4, BorderLayout.CENTER);
		panel_4.setLayout(new BorderLayout(0, 0));
		
		txtNivelForm = new JTextField();
		panel_4.add(txtNivelForm, BorderLayout.NORTH);
		txtNivelForm.setColumns(10);
//		
//		txtActuacionesNecesariasForm = new JTextField();
//		panel_4.add(txtActuacionesNecesariasForm, BorderLayout.CENTER);
//		txtActuacionesNecesariasForm.setColumns(10);
//		
//		JPanel panel_5 = new JPanel();
//		panel.add(panel_5, BorderLayout.EAST);
//	
	}
    
    public void setPlan(PlanProteccion plan){
        this.plan = plan;
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        switch(e.getActionCommand()){
            case BTN_VOLVER:
                this.dispose();
                break;
            case BTN_ADD_EMER:
                String tipo = txtTipoForm.getText();
                int codigoPlan = Integer.parseInt(txtCodigoPlanForm.getText());
                int nivel = Integer.parseInt(txtNivelForm.getText());
                oyenteVista.notificacion(OyenteVista.Evento.GET_PLAN_ID, codigoPlan);
                Emergencia emergencia = new Emergencia(tipo, 1, nivel, plan);
                oyenteVista.notificacion(OyenteVista.Evento.ADD_EMER, emergencia);
                System.out.println("Emergencia: " + emergencia.toString());
                this.dispose();
                break;
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
