/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Alerta;
import java.util.List;
import javax.swing.DefaultListModel;


/**
 *
 * @author Cristian
 */
public class PanelHistorial extends javax.swing.JPanel {
    private DefaultListModel modelo;
    private List<Alerta> historialAlertas;
    private OyenteVista oyenteVista;
    /**
     * Creates new form PanelHistorial
     */
    public PanelHistorial(OyenteVista oyenteVista) {
        this.oyenteVista = oyenteVista;
        modelo = new DefaultListModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoHistorial = new javax.swing.JLabel();
        barraHistorial = new javax.swing.JScrollPane();
        historial = new javax.swing.JList<>();

        textoHistorial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoHistorial.setText("Historial de alertas");
        textoHistorial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        historial.setModel(modelo);
        barraHistorial.setViewportView(historial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barraHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(textoHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane barraHistorial;
    private javax.swing.JList<String> historial;
    private javax.swing.JLabel textoHistorial;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Introduce un elemento a la lista de alertas
     */
    public void introducirAlertasALista(List listado) {
        historialAlertas = listado;
        modelo.clear();
        for(int indice = 0; indice<historialAlertas.size();indice++){
            Alerta alerta = historialAlertas.get(indice);
            String info = alerta.toString();
            modelo.addElement(info);
        }
        revalidate();
            
    }

}
