/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener {
    private static final String MENU_PLANES = "Menu Planes";
    private static final String MENU_EMERGENCIAS = "Menu Emergencias";
    private static final String MENU_ZONAS_SEGURIDAD = "Menu Zonas de Seguridad";
    
    private OyenteVista oyenteVista;
    /**
     * Creates new form VentanPrincipal
     */
    public VentanaPrincipal(OyenteVista oyenteVista) {
        this.oyenteVista = oyenteVista; 
        initComponents();
        
        //Hacer que el frame reciba notificaciones del menú
        jMenuItemAlbergues.addActionListener(this);
        jMenuItemAlbergues.setActionCommand("Panel Albergues");
        
        jMenuItemAlmacenes.addActionListener(this);
        jMenuItemMapaRecursos.addActionListener(this);
        jMenuItemVehiculos.addActionListener(this);
        jMenuItemVoluntarios.addActionListener(this);
        
        jMenuItemPlanes.addActionListener(this);
        jMenuItemPlanes.setActionCommand(MENU_PLANES);
        
        jMenuItemEmergencias.addActionListener(this);
        jMenuItemEmergencias.setActionCommand(MENU_EMERGENCIAS);
        
        jMenuItemIniciarSesion.addActionListener(this);
        jMenuItemRegistrarse.addActionListener(this);
        
        jMenuItemAlertas.addActionListener(this);
        jMenuItemAlertas.setActionCommand("MENU_ITEM_ALERTAS");
        
        jMenuItemZonasSeguridad.addActionListener(this);
        jMenuItemZonasSeguridad.setActionCommand(MENU_ZONAS_SEGURIDAD);
          
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPlanes = new javax.swing.JMenu();
        jMenuItemPlanes = new javax.swing.JMenuItem();
        jMenuItemEmergencias = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemVoluntarios = new javax.swing.JMenuItem();
        jMenuItemVehiculos = new javax.swing.JMenuItem();
        jMenuItemAlmacenes = new javax.swing.JMenuItem();
        jMenuItemAlbergues = new javax.swing.JMenuItem();
        jMenuItemMapaRecursos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAlertas = new javax.swing.JMenuItem();
        jMenuItemZonasSeguridad = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemIniciarSesion = new javax.swing.JMenuItem();
        jMenuItemRegistrarse = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(MAXIMIZED_BOTH);

        panelCentral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/iconoTitulo.png"))); // NOI18N

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Protección Civil");

        jMenuPlanes.setText("Planes de Protección");
        jMenuPlanes.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        jMenuItemPlanes.setText("Planes");
        jMenuItemPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlanesActionPerformed(evt);
            }
        });
        jMenuPlanes.add(jMenuItemPlanes);

        jMenuItemEmergencias.setText("Emergencias");
        jMenuPlanes.add(jMenuItemEmergencias);

        jMenuBar1.add(jMenuPlanes);

        jMenu2.setText("Gestión de Recursos");
        jMenu2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        jMenuItemVoluntarios.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMenuItemVoluntarios.setText("Voluntarios");
        jMenuItemVoluntarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVoluntariosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemVoluntarios);

        jMenuItemVehiculos.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMenuItemVehiculos.setText("Vehículos");
        jMenu2.add(jMenuItemVehiculos);

        jMenuItemAlmacenes.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMenuItemAlmacenes.setText("Almacenes");
        jMenu2.add(jMenuItemAlmacenes);

        jMenuItemAlbergues.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMenuItemAlbergues.setText("Albergues");
        jMenu2.add(jMenuItemAlbergues);

        jMenuItemMapaRecursos.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMenuItemMapaRecursos.setText("Mapa");
        jMenu2.add(jMenuItemMapaRecursos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Gestión de Alertas");
        jMenu3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        jMenuItemAlertas.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMenuItemAlertas.setText("Alertas");
        jMenu3.add(jMenuItemAlertas);

        jMenuItemZonasSeguridad.setText("Zonas de Seguridad");
        jMenu3.add(jMenuItemZonasSeguridad);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Usuario");
        jMenu4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

        jMenuItemIniciarSesion.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMenuItemIniciarSesion.setText("Iniciar Sesión");
        jMenu4.add(jMenuItemIniciarSesion);

        jMenuItemRegistrarse.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jMenuItemRegistrarse.setText("Registrarse");
        jMenuItemRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarseActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemRegistrarse);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRegistrarseActionPerformed

    private void jMenuItemVoluntariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVoluntariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVoluntariosActionPerformed

    private void jMenuItemPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlanesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPlanesActionPerformed

    
    @Override
    public void actionPerformed(ActionEvent e) {
        notificacionAControl(e.getActionCommand());
    }
    
    /**
     * Cambia el panel central
     */
    public void cambiarPanelCentral(JPanel panel){
        panelCentral.removeAll();
        panelCentral.add(panel);
    }
    
    public JPanel getPanelCentral(){
        return panelCentral;
    }
    public void notificacionAControl(String evento){
       
      switch(evento) {
        case "MENU_ITEM_ALERTAS":
            oyenteVista.notificacion(OyenteVista.Evento.MENU_ITEM_ALERTAS, null);
            break;
        case MENU_PLANES:
            System.out.println("menu planes");
            oyenteVista.notificacion(OyenteVista.Evento.MENU_PLANES, null);
            break;
        case MENU_EMERGENCIAS:
            oyenteVista.notificacion(OyenteVista.Evento.MENU_EMERGENCIAS, null);
            break;
        case MENU_ZONAS_SEGURIDAD:
            oyenteVista.notificacion(OyenteVista.Evento.MENU_ZONAS, null);
            break;
        }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenu jMenu4;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAlbergues;
    private javax.swing.JMenuItem jMenuItemAlertas;
    private javax.swing.JMenuItem jMenuItemAlmacenes;
    private javax.swing.JMenuItem jMenuItemEmergencias;
    private javax.swing.JMenuItem jMenuItemIniciarSesion;
    private javax.swing.JMenuItem jMenuItemMapaRecursos;
    private javax.swing.JMenuItem jMenuItemPlanes;
    private javax.swing.JMenuItem jMenuItemRegistrarse;
    private javax.swing.JMenuItem jMenuItemVehiculos;
    private javax.swing.JMenuItem jMenuItemVoluntarios;
    private javax.swing.JMenuItem jMenuItemZonasSeguridad;
    public javax.swing.JMenu jMenuPlanes;
    private javax.swing.JPanel panelCentral;
    // End of variables declaration//GEN-END:variables
}
