/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener {

    private OyenteVista oyenteVista;
    private JPanel panelAuxiliar;
    /**
     * Creates new form VentanPrincipal
     */
    public VentanaPrincipal(OyenteVista oyenteVista) {
        this.oyenteVista = oyenteVista; 
        initComponents();
        panelAuxiliar = panelCentral;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        panelCentral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        inicio = new javax.swing.JButton();
        planes = new javax.swing.JButton();
        recursos = new javax.swing.JButton();
        alertas = new javax.swing.JButton();
        registro = new javax.swing.JButton();
        inicioSesion = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(MAXIMIZED_BOTH);

        jButton5.setText("Registrarse");

        jButton6.setText("Iniciar sesion");

        label1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        label1.setText("PROTECCION CIVIL");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/iconoTitulo.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        inicio.setText("Inicio");
        inicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inicio.setFocusable(false);
        inicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(inicio);

        planes.setText("Planes De Proteccion");
        planes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        planes.setFocusable(false);
        planes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        planes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(planes);

        recursos.setText("Gestion De Recursos");
        recursos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        recursos.setFocusable(false);
        recursos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        recursos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(recursos);

        alertas.setText("Gestion De Alertas");
        alertas.setActionCommand("MENU_ITEM_ALERTAS");
        alertas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        alertas.setFocusable(false);
        alertas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alertas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        alertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertasActionPerformed(evt);
            }
        });
        jToolBar1.add(alertas);

        registro.setText("Registrarse");
        registro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registro.setFocusable(false);
        registro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(registro);

        inicioSesion.setText("Iniciar Sesion");
        inicioSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inicioSesion.setFocusable(false);
        inicioSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inicioSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(inicioSesion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton6))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertasActionPerformed
        notificacionAControl(evt.getActionCommand());
    }//GEN-LAST:event_alertasActionPerformed

    
    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.println(e);
        System.out.println("ACCION");
        notificacionAControl(e.getActionCommand());
    }
    
    /**
     * Cambia el panel central
     */
    public void cambiarPanelCentral(JPanel panel){
        panelCentral.removeAll();
        panelCentral.add(panel);
    }
    
    public JPanel getPanelCentral(){
        return panelCentral;
    }
    public void notificacionAControl(String evento){
       
      switch(evento) {
        case "MENU_ITEM_ALERTAS":
            panelCentral.setBackground(Color.yellow);
           oyenteVista.notificacion(OyenteVista.Evento.MENU_ITEM_ALERTAS, null);
           break;
        }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alertas;
    private javax.swing.JButton inicio;
    private javax.swing.JButton inicioSesion;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.Label label1;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JButton planes;
    private javax.swing.JButton recursos;
    private javax.swing.JButton registro;
    // End of variables declaration//GEN-END:variables
}
